server:
  port: 8090

spring:
  application:
    name: weather-service
management:
  security:
    enabled: false
service:
   baseUrl: https://query.yahooapis.com
   path: /v1/public/yql
   query: select%20*%20from%20weather.forecast%20where%20woeid%20%3D%
   format: json
   dasWeatherServiceId: das-weather-service